//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HathLibraries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HathLibraries.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v2.3.1
        /// *
        /// * Copyright 2012 Twitter, Inc
        /// * Licensed under the Apache License v2.0
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Designed and built with all the love in the world @twitter by @mdo and @fat.
        /// */.clearfix{*zoom:1}.clearfix:before,.clearfix:after{display:table;line-height:0;content:&quot;&quot;}.clearfix:after{clear:both}.hide-text{font:0/0 a;color:transparent;text-shadow:none;background-color:transparent;border:0}.input-block-level{display:block;width:100%;min-height:30px;-webkit- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Http_Css_Bootstrap {
            get {
                return ResourceManager.GetString("Http.Css.Bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap Responsive v2.3.1
        /// *
        /// * Copyright 2012 Twitter, Inc
        /// * Licensed under the Apache License v2.0
        /// * http://www.apache.org/licenses/LICENSE-2.0
        /// *
        /// * Designed and built with all the love in the world @twitter by @mdo and @fat.
        /// */.clearfix{*zoom:1}.clearfix:before,.clearfix:after{display:table;line-height:0;content:&quot;&quot;}.clearfix:after{clear:both}.hide-text{font:0/0 a;color:transparent;text-shadow:none;background-color:transparent;border:0}.input-block-level{display:block;width:100%;min-height:30 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Http_Css_Bootstrap_Responsive {
            get {
                return ResourceManager.GetString("Http.Css.Bootstrap.Responsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body
        ///{
        ///}.
        /// </summary>
        public static string Http_Css_Custom {
            get {
                return ResourceManager.GetString("Http.Css.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Http_Images_Icons_Black {
            get {
                object obj = ResourceManager.GetObject("Http.Images.Icons.Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Http_Images_Icons_White {
            get {
                object obj = ResourceManager.GetObject("Http.Images.Icons.White", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;Hentai@Home client stats&lt;/title&gt;
        ///        
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/stats/css/bootstrap.min&quot; /&gt;
        ///		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;/stats/css/bootstrap.responsive.min&quot; /&gt;        ///        
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;/stats/javascript/jquery.min&quot;&gt;&lt;/script&gt;
        ///		&lt;script type=&quot;text/javascript&quot; src=&quot;/stats/javascript/bootstrap.min&quot;&gt;&lt;/script&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        D [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Http_Index {
            get {
                return ResourceManager.GetString("Http.Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///* Bootstrap.js by @fat &amp; @mdo
        ///* Copyright 2012 Twitter, Inc.
        ///* http://www.apache.org/licenses/LICENSE-2.0.txt
        ///*/
        ///!function(e){&quot;use strict&quot;;e(function(){e.support.transition=function(){var e=function(){var e=document.createElement(&quot;bootstrap&quot;),t={WebkitTransition:&quot;webkitTransitionEnd&quot;,MozTransition:&quot;transitionend&quot;,OTransition:&quot;oTransitionEnd otransitionend&quot;,transition:&quot;transitionend&quot;},n;for(n in t)if(e.style[n]!==undefined)return t[n]}();return e&amp;&amp;{end:e}}()})}(window.jQuery),!function(e){&quot;use strict&quot;;va [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Http_Javascript_Bootstrap {
            get {
                return ResourceManager.GetString("Http.Javascript.Bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Http_Javascript_Custom {
            get {
                return ResourceManager.GetString("Http.Javascript.Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.9.1 | (c) 2005, 2012 jQuery Foundation, Inc. | jquery.org/license
        /////@ sourceMappingURL=jquery.min.map
        ///*/(function(e,t){var n,r,i=typeof t,o=e.document,a=e.location,s=e.jQuery,u=e.$,l={},c=[],p=&quot;1.9.1&quot;,f=c.concat,d=c.push,h=c.slice,g=c.indexOf,m=l.toString,y=l.hasOwnProperty,v=p.trim,b=function(e,t){return new b.fn.init(e,t,r)},x=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,w=/\S+/g,T=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,N=/^(?:(&lt;[\w\W]+&gt;)[^&gt;]*|#([\w-]*))$/,C=/^&lt;(\w+)\s*\/?&gt;(?:&lt;\/\1&gt;|)$/,k=/^[\ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Http_Javascript_jQuery {
            get {
                return ResourceManager.GetString("Http.Javascript.jQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icons_Favicon {
            get {
                object obj = ResourceManager.GetObject("Icons.Favicon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-agent: *
        ///Disallow: /.
        /// </summary>
        public static string Text_Robots {
            get {
                return ResourceManager.GetString("Text.Robots", resourceCulture);
            }
        }
    }
}
